language: python
python:
  - "2.7"
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libseccomp-dev
install:
 - sudo python setup.py install
script: cd tests && sudo python test.py
